import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav style={{ display: "flex", gap: "1rem" }}>
          <Link href="/">staging</Link>
          <Link href="/production">production</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
